{% set name = "spleeter" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ecd3518a98f9978b9088d1cb2ef98f766401fd9007c2bf72a34e5b5bc5a6fdc3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37 or py>38]
  entry_points:
    - spleeter = spleeter.__main__:entrypoint

requirements:
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - numpy
    - scipy
    - ffmpeg
    - freetype
    - requests >=2.21.0,<3
    - setuptools
    - importlib_resources  # [py<37]
    - tensorflow ==2.3.0  # [linux]
    - pandas
    - ffmpeg-python
    - norbert
    - librosa

test:
  imports:
    - spleeter
    - spleeter.commands
    - spleeter.model
    - spleeter.utils
    - spleeter.separator

about:
  home: https://github.com/deezer/spleeter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Deezer source separation library with pretrained models based on tensorflow.
  doc_url: https://github.com/deezer/spleeter/wiki
  dev_url: https://github.com/deezer/spleeter

extra:
  recipe-maintainers:
    - Faylixe
    - romi1502
