{% set name = "spleeter" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c98331ce1e9db5cd686a5c4856c196654291ea90447caa9676a3869f37934ed4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36 or py>37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - setuptools
    - importlib_resources  # [py<37]
    - tensorflow ==1.14.0
    - pandas ==0.25.1
    - ffmpeg-python
    - norbert
    - librosa ==0.7.2

test:
  imports:
    - spleeter
    - spleeter.commands
    - spleeter.model
    - spleeter.utils
    - spleeter.separator

about:
  home: https://github.com/deezer/spleeter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Deezer source separation library with pretrained models based on tensorflow.
  doc_url: https://github.com/deezer/spleeter/wiki
  dev_url: https://github.com/deezer/spleeter

extra:
  recipe-maintainers:
    - Faylixe
    - romi1502
