{% set name = "spleeter" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 148cb583000c0f45e8905dd7073dd86d4cdd9dd8f54a145c8ce97d6658033c42

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<36 or py>37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - setuptools
    - importlib_resources  # [py<37]
    - tensorflow ==1.14.0
    - pandas ==0.25.1
    - ffmpeg-python
    - norbert

test:
  imports:
    - spleeter
    - spleeter.commands
    - spleeter.model
    - spleeter.utils
    - spleeter.separator

about:
  home: https://github.com/deezer/spleeter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Deezer source separation library with pretrained models based on tensorflow.'
  doc_url: https://github.com/deezer/spleeter/wiki
  dev_url: https://github.com/deezer/spleeter

extra:
  recipe-maintainers:
    - Faylixe
    - romi1502
