{% set name = "spleeter" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 45587ce30dcbd4cc21e87d9ae73f5e71b7b4a533eb6731f11bfe93ce6299c50a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37 or py>38]
  entry_points:
    - spleeter = spleeter.__main__:entrypoint

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - setuptools >=41.4
    - ca-certificates
    - tzdata
    - scipy >=1.4.1
    - six >=1.5
    - importlib_resources  # [py<37]
    - tensorflow ==2.3.0  # [linux]
    - tensorflow ==2.0.0  # [osx]
    - tensorflow ==2.1.0  # [win]
    - pandas ==1.1.2
    - ffmpeg-python ==0.2.0
    - norbert ==0.2.1
    - librosa ==0.8.0

test:
  imports:
    - spleeter
    - spleeter.commands
    - spleeter.model
    - spleeter.utils
    - spleeter.separator

about:
  home: https://github.com/deezer/spleeter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Deezer source separation library with pretrained models based on tensorflow.
  doc_url: https://github.com/deezer/spleeter/wiki
  dev_url: https://github.com/deezer/spleeter

extra:
  recipe-maintainers:
    - Faylixe
    - romi1502
